"""Add nullable filepath to Receipt

Revision ID: bcb6d5934e63
Revises: a7dabffa1b85
Create Date: 2025-07-23 04:35:14.306819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb6d5934e63'
down_revision = 'a7dabffa1b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
